# Generated by Django 2.2.5 on 2019-09-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='imgName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
